config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.order('created_at DESC')
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/_feed.html.erb
<div id="feed">
  <h2>Home</h2>

  <div id="feed-owner">
    <div class="feed-owner-left">
      <h5 class="middle">For You</h5>
    </div>
    <div class="feed-owner-right">
      <h5 class="middle">Following</h5>
    </div>
  </div>

  <div id="tweet">
    <div id="tweet-avatar">
      <%= image_tag('https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg?size=626&ext=jpg&ga=GA1.1.417348283.1689604607&semt=ais', class: 'avatar-image') %>
    </div>

    <%# <div id="make-tweet"> %>
      <%# <%= simple_form_for(@tweet) do |f| %> 
        <%# <%= f.error_notification %> 

        <%# <div class="form-inputs"> %>
          <%# <%= f.input :name %>  
        <%# </div> %>
        <%# <div class="form-actions"> %>
            <%# <%= f.button :submit %>  
        <%# </div> %>
      <%# <% end %> 
    <%# </div> %>
  </div>
</div>

app/views/layouts/_feed.html.erb
<div id="feed">
  <h2>Home</h2>

  <div id="feed-owner">
    <div class="feed-owner-left">
      <h5 class="middle">For You</h5>
    </div>
    <div class="feed-owner-right">
      <h5 class="middle">Following</h5>
    </div>
  </div>

  <div id="tweet">
    <div id="tweet-avatar">
      <%= image_tag('https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg?size=626&ext=jpg&ga=GA1.1.417348283.1689604607&semt=ais', class: 'avatar-image') %>
    </div>

    <div id="make-tweet">
      <%# <%= simple_form_for(@account) do |f| %> 
        <%# <%= f.error_notification %> 

        <%# <div class="form-inputs"> %>
          <%# <%= f.input :name %> 
        <%# </div> %>

        <%# <div class="form-actions"> %>
          <%# <%= f.button :submit %> 
        <%# </div> %>
      <%# <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Twitter clone</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>

    <%= yield %>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div id="feed">
  <h2>Home</h2>

  <div id="feed-owner">
    <div class="feed-owner-left">
      <h5 class="middle">For You</h5>
    </div>
    <div class="feed-owner-right">
      <h5 class="middle">Following</h5>
    </div>
  </div>

  <div id="tweet">
    <div id="tweet-avatar">
      <%# image_tag('https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg?size=626&ext=jpg&ga=GA1.1.417348283.1689604607&semt=ais', class: 'avatar-image') %>
    </div>

    <div id="make-tweet">
      <%= simple_form_for(@tweet) do |f| %>
        <%= f.error_notification %> 

        <div class="form-inputs">
          <%= f.input :tweet %>
        </div>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>

  <% @tweets.each do |tweet| %>
    <div id="feed-news">
      <strong><%= tweet.user.name %></strong>
      <strong><%= tweet.user.username %></strong>
      <p><%= tweet.tweet %></p>
    </div>
  <% end %>
  
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :tweet %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tweets/_navbar.html.erb
<div id="navbar">
  <i class="fa-brands fa-twitter fa-2xl"></i>

  <div id="navbar-links">
    <div id="navbar-logo">
      <ul>
        <li>
          <i class="fa-solid fa-house"></i>
        </li>
        <li>
          <i class="fa-solid fa-magnifying-glass"></i>
        </li>
        <li>
          <i class="fa-solid fa-bell"></i>
        </li>
        <li>
          <i class="fa-solid fa-message"></i>
        </li>
        <li>
          <i class="fa-solid fa-list"></i>
        </li>
        <li>
          <i class="fa-solid fa-bookmark"></i>
        </li>
        <li>
          <i class="fa-solid fa-certificate"></i>
        </li>
        <li>
          <i class="fa-solid fa-user"></i>
        </li>
        <li>
          <i class="fa-solid fa-bars"></i>
        </li>
      </ul>
    </div>
    <div id="navbar-text">
      <ul>
        <li>
          Home
        </li>
        <li>
          Explore
        </li>
        <li>
          Notifications
        </li>
        <li>
          Messages
        </li>
        <li>
          Lists
        </li>
        <li>
          Bookmarks
        </li>
        <li>
          Verified
        </li>
        <li>
          Profile
        </li>
        <li>
          More
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/tweets/_trends.html.erb
<div id="trends">

</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div id="container">
  <%= render 'navbar' %>
  <%= render 'feed' %>
  <%= render 'trends' %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>